name: Ambiente Dsenvolvimento

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
  jobs: 
    build:
      name: Compilação
      runs-on: ubuntu-latest
      
      steps:
      - name: Git Chekcout
        uses: actions/checkout@v3
      - name: Configurar o JDK 11
        uses: actions/checkout@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Compilação
        run: mvn -B compila --file pom.xml
          
